name: Daily Trading Analysis

on:
  schedule:
    # Run at 12:30 PM UTC (7:30 AM ET / 8:30 AM EDT) - 30 minutes before NY session open
    - cron: '30 12 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  trading-analysis:
    runs-on: ubuntu-latest
    
    # Add permissions for downloading artifacts via API
    permissions:
      contents: read
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: |
        mkdir -p trading_session
        echo "📁 Output directory created"
        
    - name: Run trading analysis with session continuity
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTIONS: true
      run: |
        echo "🚀 Starting trading analysis with previous session continuity..."
        echo "📥 Previous session data will be automatically downloaded if available..."
        python market_planner.py
        
    - name: Upload trading session artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trading-session-${{ github.run_number }}
        path: trading_session/
        retention-days: 30
        
