name: Daily Trading Analysis

on:
  schedule:
    # Run at 7:00 PM Japan Standard Time (UTC+9) on weekdays only
    - cron: '0 10 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  trading-analysis:
    runs-on: ubuntu-latest
    
    # Add permissions for downloading artifacts via API
    permissions:
      contents: read
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: |
        mkdir -p trading_session
        
    - name: Download previous session artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "📥 Attempting to download previous session data..."
        # The Python script will handle downloading previous artifacts via GitHub API
        # This step ensures the environment is set up correctly
        
    - name: Test date filtering logic
      run: |
        echo "🧪 Running date filtering tests..."
        python -m unittest test_date_filtering.py -v
        python test_integration.py
        
    - name: Test persistence mechanism
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "🧪 Testing persistence mechanism..."
        python test_persistence_standalone.py
        
    - name: Test JSON parsing
      run: |
        echo "🧪 Testing JSON parsing..."
        python test_json_parsing.py
        
    - name: Run trading analysis
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python market_planner.py
        
    - name: Upload trading session artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trading-session-${{ github.run_number }}
        path: trading_session/
        retention-days: 30
        
