name: Daily Trading Analysis

on:
  schedule:
    # Run at 7:00 PM Japan Standard Time (UTC+9) on weekdays only
    - cron: '0 10 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  trading-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: |
        mkdir -p trading_session
        
    - name: Run trading analysis
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python market_planner.py
        
    - name: Upload trading session artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trading-session-${{ github.run_number }}
        path: trading_session/
        retention-days: 30
        
    - name: Commit and push results (optional)
      if: always()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add trading_session/
        git commit -m "Update trading analysis results" || echo "No changes to commit"
        git push || echo "Push failed or no changes"
